<a href="https://colab.research.google.com/github/shenzhun/machine-learning-brushup/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#Array

In [0]:
A = np.array([1, 2, 3])
for i in A:
  print(i)

A.shape

B = np.array([[1], [2], [3]])
B.shape

1
2
3


(3, 1)

In [0]:
2 * A

array([2, 4, 6])

In [0]:
A ** 2
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

## Indexing

In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


# Dot Product

In [0]:
a = np.array([1,2])
b = np.array([2,1])
dot = a * b
print(dot)
print(np.sum(a*b), (a*b).sum())
np.dot(a, b)
a.dot(b)
b.dot(a)

np.linalg.norm(a)

[2 2]
4 4


2.23606797749979

# Vector and Matrix

In [0]:
M = np.array([[1,2], [3, 4]])
L = [[1,2], [3, 4]]
L[0]
L[0][0]
M[0][0]
M[0, 0]

M.T

array([[1, 3],
       [2, 4]])

## Filtering

# Generating Matrices

In [6]:
Z = np.zeros(10)
print(Z)

Z = np.zeros((10, 10))
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.random.random((10, 10))

array([[0.32108714, 0.9871256 , 0.03394738, 0.94913969, 0.75456768,
        0.68990812, 0.29779663, 0.3362326 , 0.28277077, 0.01963986],
       [0.14608894, 0.01984178, 0.04083589, 0.33999674, 0.41404978,
        0.42596016, 0.44272689, 0.22690105, 0.82530216, 0.63755427],
       [0.75219351, 0.21440846, 0.00916578, 0.75043872, 0.93881645,
        0.50914506, 0.41432537, 0.03349775, 0.91086495, 0.60869792],
       [0.80407249, 0.47938034, 0.70433889, 0.77845948, 0.36751809,
        0.01676428, 0.28506869, 0.10829477, 0.50955047, 0.338198  ],
       [0.02416267, 0.87431808, 0.25411729, 0.26197707, 0.7882777 ,
        0.74573534, 0.70688086, 0.0691838 , 0.1387246 , 0.66406717],
       [0.22921546, 0.25632342, 0.84400971, 0.38283172, 0.36745642,
        0.52663953, 0.98863517, 0.51857481, 0.39958532, 0.1308098 ],
       [0.368471  , 0.10823888, 0.1447138 , 0.78750076, 0.02654921,
        0.06710264, 0.5664729 , 0.71007407, 0.23298807, 0.86999465],
       [0.50689661, 0.3976454 , 0.2389730

In [13]:
# gaussin 
G = np.random.randn(10, 10)
G = np.random.standard_normal((10, 10))
G.mean()
G.var()

1.1537734863704017

In [19]:
A = np.array([[5, 6], [7, 8]])
B = np.array([[1, 2], [3, 4]])

# element wise
A * B 

# matrix product, dot product
A.dot(B)


array([[23, 34],
       [31, 46]])

In [23]:
A = np.array([[1,2], [3, 4]])
Ainv = np.linalg.inv(A)
print(Ainv)

Ainv.dot(A)

[[-2.   1. ]
 [ 1.5 -0.5]]


array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [24]:
np.linalg.det(A)

-2.0000000000000004

In [26]:
np.diag(A)
np.diag([1, 2])

array([[1, 0],
       [0, 2]])

# Outer Product
https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html

In [27]:
a = np.array([1, 2])
b = np.array([3, 4])
np.outer(a, b)

array([[3, 4],
       [6, 8]])

# Inner Product

In [28]:
a.dot(b)

11

In [32]:
a = np.eye(3)
np.trace(a)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Nana

In [0]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

np.array([np.nan, 1, 2], dtype=np.int32)


array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


ValueError: ignored

# Infinity

In [0]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 5])
print(repr(arr))

np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   5.])


OverflowError: ignored