<a href="https://colab.research.google.com/github/shenzhun/machine-learning-brushup/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#Array

In [20]:
A = np.array([1, 2, 3])
for i in A:
  print(i)

A.shape

B = np.array([[1], [2], [3]])
B.shape

1
2
3


(3, 1)

In [4]:
2 * A

array([2, 4, 6])

In [6]:
A ** 2
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

## Indexing

In [24]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


# Dot Product

In [12]:
a = np.array([1,2])
b = np.array([2,1])
dot = a * b
print(dot)
print(np.sum(a*b), (a*b).sum())
np.dot(a, b)
a.dot(b)
b.dot(a)

np.linalg.norm(a)

[2 2]
4 4


2.23606797749979

# Vector and Matrix

In [17]:
M = np.array([[1,2], [3, 4]])
L = [[1,2], [3, 4]]
L[0]
L[0][0]
M[0][0]
M[0, 0]

M.T

array([[1, 3],
       [2, 4]])

## Filtering

# Nana

In [0]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

np.array([np.nan, 1, 2], dtype=np.int32)


array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


ValueError: ignored

# Infinity

In [0]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 5])
print(repr(arr))

np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   5.])


OverflowError: ignored