<a href="https://colab.research.google.com/github/shenzhun/machine-learning-brushup/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# Nana

In [0]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

np.array([np.nan, 1, 2], dtype=np.int32)


array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


ValueError: ignored

# Infinity

In [0]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 5])
print(repr(arr))

np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   5.])


OverflowError: ignored