<a href="https://colab.research.google.com/github/shenzhun/CSCI-561/blob/master/sgd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Standard Gradient Descent

In [0]:
import torch
from torch import tensor, nn

In [0]:
n = 100
a = tensor([2.,1.])

In [25]:
x = torch.ones(n, 2)
x[:, 0].uniform_(-1, 1)
x[:5]

tensor([[-0.1783,  1.0000],
        [-0.8236,  1.0000],
        [-0.0129,  1.0000],
        [-0.6885,  1.0000],
        [-0.1275,  1.0000]])

In [26]:
y = x@a + torch.rand(n)
y[:5]

tensor([1.0598, 0.3301, 0.9778, 0.4377, 1.1871])

In [0]:
def mse(y_hat, y):
  return ((y_hat - y) ** 2).mean()

In [0]:
a = nn.Parameter(tensor([1., 1.]))
def train():
  y_hat = x@a
  loss = mse(y_hat, y)
  if epoch % 10 == 0:
    print(loss)

  loss.backward()
  with torch.no_grad():
    a.sub_(lr * a.grad)
    a.grad.zero_()


In [36]:
lr = 0.001
for epoch in range(100):
  train()

a

tensor(0.5187, grad_fn=<MeanBackward0>)
tensor(0.5098, grad_fn=<MeanBackward0>)
tensor(0.5011, grad_fn=<MeanBackward0>)
tensor(0.4926, grad_fn=<MeanBackward0>)
tensor(0.4844, grad_fn=<MeanBackward0>)
tensor(0.4764, grad_fn=<MeanBackward0>)
tensor(0.4686, grad_fn=<MeanBackward0>)
tensor(0.4610, grad_fn=<MeanBackward0>)
tensor(0.4536, grad_fn=<MeanBackward0>)
tensor(0.4465, grad_fn=<MeanBackward0>)


Parameter containing:
tensor([1.1172, 1.1653], requires_grad=True)

# SGD
