<a href="https://colab.research.google.com/github/shenzhun/machine-learning-prep/blob/master/tensorflow/day10_rules_of_using_autograph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
@tf.function
def np_random():
  a = np.random.randn(3,3)
  tf.print(a)

@tf.function
def tf_random():
  a = tf.random.normal((3, 3))
  tf.print(a)

In [3]:
np_random()
np_random()

array([[ 1.48231012,  0.08311213,  0.2937399 ],
       [ 1.23145541,  0.92783413,  0.80188662],
       [-0.48159263, -0.58638862,  0.3196945 ]])
array([[ 1.48231012,  0.08311213,  0.2937399 ],
       [ 1.23145541,  0.92783413,  0.80188662],
       [-0.48159263, -0.58638862,  0.3196945 ]])


In [4]:
tf_random()
tf_random()

[[-1.83632231 -0.936836 0.213924333]
 [0.0287378896 0.825910926 -1.56398857]
 [-0.497171223 -0.754858673 1.84749389]]
[[0.836282492 0.60368365 0.0797789395]
 [-0.622425377 0.226121426 0.736842871]
 [0.71754247 -1.70847559 -1.59923077]]


In [5]:
x = tf.Variable(1.0, dtype=tf.float32)

@tf.function
def outer_var():
  x.assign_add(1.0)
  tf.print(x)
  return(x)

outer_var()
outer_var()

2
3


<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [7]:
@tf.function
def inner_var():
  x = tf.Variable(1.0, dtype=tf.float32)
  x.assign_add(1.0)
  tf.print(x)
  return x

inner_var()
inner_var()

ValueError: ignored

In [11]:
tensor_list = []

# @tf.function
def append_tensor(x):
  tensor_list.append(x)
  return tensor_list

append_tensor(tf.constant(5.0))
append_tensor(tf.constant(6.0))
print(tensor_list)

[<tf.Tensor: shape=(), dtype=float32, numpy=5.0>, <tf.Tensor: shape=(), dtype=float32, numpy=6.0>]


In [12]:
tensor_list = []

@tf.function
def append_tensor(x):
  tensor_list.append(x)
  return tensor_list

append_tensor(tf.constant(5.0))
append_tensor(tf.constant(6.0))
print(tensor_list)

[<tf.Tensor 'x:0' shape=() dtype=float32>]
