<a href="https://colab.research.google.com/github/shenzhun/machine-learning-prep/blob/master/tensorflow/day1_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
i = tf.constant(1)
l = tf.constant(1, dtype=tf.int64)
f = tf.constant(1.23)
d = tf.constant(3.14, dtype = tf.double)
s = tf.constant("hello world")
b = tf.constant(True)

In [3]:
print(tf.int64 == np.int64)
print(tf.bool == np.bool)
print(tf.double == np.float64)
print(tf.string == np.unicode)

True
True
True
False


In [6]:
scalar = tf.constant(True)

print(tf.rank(scalar), scalar.numpy().ndim)

tf.Tensor(0, shape=(), dtype=int32) 0


In [7]:
vector = tf.constant([1.0, 2.0, 3.0, 4.0])
print(tf.rank(vector), np.ndim(vector.numpy()))

tf.Tensor(1, shape=(), dtype=int32) 1


In [9]:
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print(tf.rank(matrix).numpy(), np.ndim(matrix))

2 2


In [11]:
tensor3 = tf.constant([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])
print(tensor3, tf.rank(tensor3))

tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32) tf.Tensor(3, shape=(), dtype=int32)


In [13]:
tensor4 = tf.constant([[[[1.0, .0], [2.0, 2.0]], [[3.0, 3.0], [4.0, 4.0]]]])
print(tensor4, tf.rank(tensor4))

tf.Tensor(
[[[[1. 0.]
   [2. 2.]]

  [[3. 3.]
   [4. 4.]]]], shape=(1, 2, 2, 2), dtype=float32) tf.Tensor(4, shape=(), dtype=int32)


Cast

In [14]:
h = tf.constant([123, 456], dtype=tf.int32)
f = tf.cast(h, tf.float32)
print(h.dtype, f.dtype)

<dtype: 'int32'> <dtype: 'float32'>


In [15]:
y = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print(y.numpy(), y.shape)

[[1. 2.]
 [3. 4.]] (2, 2)


In [16]:
u = tf.constant(u"Hello World")
print(u.numpy(), u.numpy().decode("utf-8"))

b'Hello World' Hello World
