<a href="https://colab.research.google.com/github/shenzhun/machine-learning-prep/blob/master/tensorflow/day11_mechanisms_of_autograph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

@tf.function(autograph=True)
def myadd(a, b):
  for i in tf.range(3):
    tf.print(i)
  c = a+b
  print("tracing")
  return c

In [3]:
myadd(tf.constant("hello"), tf.constant("world"))

tracing
0
1
2


<tf.Tensor: shape=(), dtype=string, numpy=b'helloworld'>

In [4]:
myadd(tf.constant("good"),tf.constant("morning"))

0
1
2


<tf.Tensor: shape=(), dtype=string, numpy=b'goodmorning'>

In [5]:
myadd(tf.constant(1),tf.constant(2))

tracing
0
1
2


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [6]:
myadd("hello","world")
myadd("good","morning")

tracing
0
1
2
tracing
0
1
2


<tf.Tensor: shape=(), dtype=string, numpy=b'goodmorning'>